name: gyan_ai
description: "Gyan-AI: The AI-Powered Learning Companion"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  json_annotation: ^4.9.0
  
  # Local Storage
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  
  # Video Player
  video_player: ^2.8.2
  chewie: ^1.5.0
  
  # Connectivity
  connectivity_plus: ^4.0.2
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Analytics & Error Reporting
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  sentry_flutter: ^8.9.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  dartz: ^0.10.1
  get_it: ^7.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Testing
  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/
    - assets/videos/
    - .env.local
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
